apiVersion: v1
kind: ConfigMap
metadata:
  name: dremio-config
data:
  {{- tpl (.Files.Glob "config/*").AsConfig . | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-script
data:
  log-to-console.sh: |-
    #!/bin/sh
    while true; do 
      sleep 10
      tail -f "$1" &
      while [[ -f $1 ]]; do 
        sleep 0.1
      done
      kill $! 2>/dev/null
    done
